version: "3.0"
services:
  db:
    image: postgres:9
    ports: 
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claper"]
      interval: 5s
      timeout: 5s
      retries: 10  
  app:
    build: .
    ports: 
      - 4000:4000
    volumes:
      - uploads:/app/uploads
    environment:
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: local
      ENDPOINT_PORT: 4000
      PRESENTATION_STORAGE: local
      MAX_FILE_SIZE_MB: 15
      ENABLE_ACCOUNT_CREATION: true
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres-data:
  uploads:
